function mountPrompt(x){
 const host=document.getElementById('promptEditor'), lesson=x.id==='lesson'; let mode='example';
 const values=Object.fromEntries((x.fields||[]).map(f=>[f.key,f.value])); let drafts={template:x.template,example:x.prompt};
 const fields=x.fields?`<details id="lessonFields"${lesson?' open':''}><summary>${lesson?'Входные данные — измените под свой урок':'Заполнить для своего урока'}</summary><div class="prompt-fields">${x.fields.map(f=>`<label>${esc(f.label)}<textarea data-field="${f.key}" rows="2">${esc(f.value)}</textarea></label>`).join('')}</div><p class="small">Промпт ниже обновляется сразу.</p></details>`:'';
 host.innerHTML=`<div class="row prompt-tabs"><button data-mode="template">Шаблон</button><button data-mode="example" class="primary">Заполненный шаблон</button></div>${fields}<p class="small" id="modeHint"></p><textarea id="prompt" aria-label="Промпт для модели"></textarea><div class="row" style="margin-top:10px"><button id="copy" class="primary">Скопировать промпт</button><button id="restore">Вернуть исходный</button><a class="btn" href="https://chat.deepseek.com/" target="_blank" rel="noopener">Открыть DeepSeek ↗</a><a class="btn" href="https://chatgpt.com/" target="_blank" rel="noopener">Открыть ChatGPT ↗</a></div><div id="copyStatus" class="small"></div>`;
 const area=host.querySelector('#prompt'), make=()=>x.template.replace(/\{\{(\w+)\}\}/g,(_,k)=>values[k]||'[не указано]');
 function show(){area.value=drafts[mode];host.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('primary',b.dataset.mode===mode));host.querySelector('#modeHint').textContent=mode==='template'?'Шаблон с полями для замены.':'Полный промпт готов к копированию.'}
 host.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{drafts[mode]=area.value;mode=b.dataset.mode;show()});
 host.querySelector('#restore').onclick=()=>{drafts[mode]=mode==='template'?x.template:x.prompt;show()};
 host.querySelector('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(area.value);host.querySelector('#copyStatus').textContent='Скопировано.'}catch{area.focus();area.select();host.querySelector('#copyStatus').textContent='Текст выделен. Нажмите Ctrl+C.'}};
 host.querySelectorAll('[data-field]').forEach(e=>e.oninput=()=>{values[e.dataset.field]=e.value.trim()||'[не указано]';drafts.example=make();if(mode==='example')area.value=drafts.example;host.querySelector('#copyStatus').textContent='Промпт обновлён.'});show();
}
