// Interaction pattern adapted from LitRes lesson_presentations/src/trainer.js.
function mountPrompt(x){
 const host=document.getElementById('promptEditor');let mode='example';const values=Object.fromEntries((x.fields||[]).map(f=>[f.key,f.value]));let drafts={template:x.template,example:x.prompt};
 host.innerHTML=`<div class="row prompt-tabs" role="group" aria-label="Вид промпта"><button data-prompt-mode="template" aria-pressed="false">Шаблон</button><button data-prompt-mode="example" class="primary" aria-pressed="true">Заполненный шаблон</button></div>${x.fields?`<details id="lessonFields"><summary>Заполнить для своего урока</summary><div class="prompt-fields">${x.fields.map(f=>`<label>${esc(f.label)}<textarea data-field="${f.key}" rows="2">${esc(f.value)}</textarea></label>`).join('')}</div><button id="applyFields">Собрать мой промпт</button><p class="small">Кнопка заменит текст заполненного шаблона значениями полей. Требования к источникам и проверке сохранятся.</p></details>`:''}<p class="small" id="modeHint"></p><textarea id="prompt" aria-label="Промпт для модели"></textarea><div class="row" style="margin-top:10px"><button id="copy" class="primary">Скопировать промпт</button><button id="restore">Вернуть исходный</button><a class="btn" href="https://chat.deepseek.com/" target="_blank" rel="noopener">Открыть DeepSeek ↗</a><a class="btn" href="https://chatgpt.com/" target="_blank" rel="noopener">Открыть ChatGPT ↗</a></div><div id="copyStatus" class="small" role="status"></div><p class="small">Скопируйте текст и вставьте его в выбранный чат. ${x.id==='lesson'?'Включите поиск, если он доступен, приложите школьные документы; сначала проверьте таблицу источников.':'Если результат — HTML, сохраните полный код в файл .html и откройте в браузере.'}</p>`;
 const area=host.querySelector('#prompt');function show(){area.value=drafts[mode];host.querySelectorAll('[data-prompt-mode]').forEach(b=>{const on=b.dataset.promptMode===mode;b.classList.toggle('primary',on);b.setAttribute('aria-pressed',String(on))});host.querySelector('#modeHint').textContent=mode==='template'?'Замените поля в скобках своими данными. Обязательные требования уже включены.':'Готовый пример. Текст можно отредактировать перед копированием.';host.querySelector('#copyStatus').textContent=''}
 host.querySelectorAll('[data-prompt-mode]').forEach(b=>b.onclick=()=>{drafts[mode]=area.value;mode=b.dataset.promptMode;show()});
 host.querySelector('#restore').onclick=()=>{drafts[mode]=mode==='template'?x.template:x.prompt;show()};
 host.querySelector('#copy').onclick=async()=>{drafts[mode]=area.value;try{await navigator.clipboard.writeText(area.value);host.querySelector('#copyStatus').textContent='Скопировано. Вставьте промпт в чат.'}catch{area.focus();area.select();host.querySelector('#copyStatus').textContent='Текст выделен. Нажмите Ctrl+C или «Копировать».'}};
 if(x.fields)host.querySelector('#applyFields').onclick=()=>{host.querySelectorAll('[data-field]').forEach(e=>values[e.dataset.field]=e.value.trim()||'[не указано]');drafts.template=mode==='template'?area.value:drafts.template;drafts.example=x.template.replace(/\{\{(\w+)\}\}/g,(_,key)=>values[key]);mode='example';show();host.querySelector('#lessonFields').open=false;host.querySelector('#copyStatus').textContent='Промпт собран. Проверьте данные и скопируйте текст.'};show();
}
